import type { PlanetName, PlanetaryPosition } from "./chart.js";
import type { GemstoneName } from "./gemstone-rules.js";
import type { DashaPeriod, TransitSnapshot } from "./dasha.js";
import type { NumerologyProfile } from "./numerology.js";
import type { EnrichedGemstoneCandidate } from "./gemology.js";

/**
 * The six concern categories from the original architecture spec
 * (Section 6, Situation Understanding Agent). Selecting one of these
 * is NOT treated as an astrological fact about the person — it only
 * tells the Explanation Agent which of the already-computed chart
 * data to narrate about, per the architecture's explicit instruction
 * that this agent must "classify the user's stated concern without
 * treating it as an astrological fact."
 */
export type SituationConcern = "career" | "finance" | "health" | "marriage" | "litigation" | "education";

/**
 * Everything the Explanation Agent needs to narrate, bundled from
 * types already in shared — deliberately NOT importing the
 * orchestrator's PipelineResult, so this package never depends on
 * the orchestrator (the orchestrator constructs this from its own
 * PipelineResult fields when calling the agent).
 */
export interface ExplanationContext {
  ascendantSignName: string;
  moonNakshatraName: string;
  planets: PlanetaryPosition[];
  currentDashaPeriod: DashaPeriod[];
  numerology: NumerologyProfile;
  enrichedCandidates: EnrichedGemstoneCandidate[];
  transitSnapshot: TransitSnapshot;
  concerns: SituationConcern[];
}

export const ALL_SITUATION_CONCERNS: SituationConcern[] = [
  "career", "finance", "health", "marriage", "litigation", "education",
];

/**
 * Classical Navagraha remedy correspondences for one planet — mantra,
 * presiding deity, traditional donation items, and fasting day. This
 * is settled traditional content (same category as the gemstone-
 * planet mapping), not something the Explanation Agent invents.
 * Regional traditions vary somewhat on specifics (e.g. exact donation
 * items); this reflects commonly-cited mainstream correspondences.
 */
export interface RemedyProfile {
  planet: PlanetName;
  deity: string;
  mantra: string;
  donationItems: string[];
  fastingDay: string;
}

export interface ExplanationSection {
  concern: SituationConcern;
  /** Plain-language explanation text, generated by the Explanation
   *  Agent but grounded entirely in the deterministic + rule-graph +
   *  gemology data already computed — see the system prompt in the
   *  explanation package for the constraints placed on this text. */
  text: string;
}

export interface ExplanationResult {
  requestId: string;
  sections: ExplanationSection[];
  /** Remedy data referenced for the shortlisted gemstone candidates'
   *  planets, attached separately from the narrated text so it stays
   *  auditable against the RemedyProfile data it came from. */
  remedies: { forGemstone: GemstoneName; remedy: RemedyProfile }[];
  /** Populated if the Consumer Protection Agent's banned-phrase filter
   *  caught anything in the LLM output before this was returned —
   *  should always be empty; a non-empty array means content was
   *  redacted and is worth investigating, not silently trusting. */
  flaggedAndRedacted: string[];
  disclaimer: string;
}
